apiVersion: apps/v1
kind: Deployment
metadata:
  name: ticketing-orders-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orders
  template:
    metadata:
      labels:
        app: orders
    spec:
      containers:
        - name: orders
          image: jinchenhu/orders
          env:
            - name: MONGO_URI
              value: "mongodb://ticketing-orders-mongo-srv:27017/orders"
            - name: NATS_URL
              value: "http://ticketing-nats-srv:4222"
            - name: NATS_CLUSTER_ID
              value: ticketing
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  key: JWT_KEY
                  name: jwt-secret

---
apiVersion: v1
kind: Service
metadata:
  name: ticketing-orders-srv
spec:
  selector:
    app: orders
  ports:
    - name: orders
      port: 3000
      targetPort: 3000
      protocol: TCP
