apiVersion: apps/v1
kind: Deployment
metadata:
  name: ticketing-payments-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payments
  template:
    metadata:
      labels:
        app: payments
    spec:
      containers:
        - name: payments
          image: jinchenhu/payments
          env:
            - name: MONGO_URI
              value: "mongodb://ticketing-payments-mongo-srv:27017/payments"
            - name: NATS_URL
              value: "http://ticketing-nats-srv:4222"
            - name: NATS_CLUSTER_ID
              value: ticketing
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  key: JWT_KEY
                  name: jwt-secret

---
apiVersion: v1
kind: Service
metadata:
  name: ticketing-payments-srv
spec:
  selector:
    app: payments
  ports:
    - name: payments
      port: 3000
      targetPort: 3000
      protocol: TCP
