# name of the workflow
name: tests-auth

on:
  pull_request:
    paths:
      - "auth/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"
      - run: cd auth
      - name: Install dependencies
        run: npm install
      - run: npm run test:ci
        env:
          JWT_KEY: ${{secrets.JWT_KEY}}
