# name of the workflow
name: tests-tickets

on:
  pull_request:
    paths:
      - "tickets/**"
      - ".github/workflows/tests-tickets.yml"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"
      - run: |
          cd tickets
          npm ci
          npm run test:ci
        env:
          JWT_KEY: ${{secrets.JWT_KEY}}
